### ISSUE TITLE
Feature Request: Disable Upgrade Process per OS

### ISSUE THREAD

**Issue by ryanmerolle** [alsigna/netbox-software-manager#1]
I would love this model to be extended to more OS in order to track golden firmware drift.

Would you have any interest in being able to allow a user to disable the upgrade process and track software versions for more platform/NOS'?

Given standard NAPALM drivers already leveraged in NetBox and included in the netbox-docker, you could use NAPALM to get the software version from the device using the already set NAPALM user and password settings in NetBox.

With those model, more users could leverage the plugin for SoT type functionality, but leverage their existing workflows to upgrade their devices (ansible, python, salt, vendor specific platforms).

**Comment by ryanmerolle** [comment]
By the way, thanks for contributing this!  Awesome job!

**Comment by alsigna** [comment]
hi, did not completely get idea. you asked about assignment gold image to PID without uploading, just for tracking purpose?

**Comment by ryanmerolle** [comment]
Sorry I apparently missed the comment!

I think your process of tracking and upgrading is a good idea.

Use cases where it would be valuable to be able to track in a data model the "standard OS version" per model/device-type without the upgrade process being enabled:

- Depending on who have access to netbox, some people would be hesitant to allow the upgrade process to even be enabled, but would.
- Where an OS upgrade process is not supported.  (but again valuable to pull the version number and associated link from the GUI and API for their existing upgrade workflow via Ansible, Nornir, etc.)

**Comment by ryanmerolle** [comment]
Let me know if you need a better write up

**Comment by alsigna** [comment]
Hi, i got the idea, will try to add option just to set target (golden) SW version without uploading image. For tracking purpose only.
