### ISSUE TITLE
Feature Request: Allow for HTTP/HTTPS Server in place of FTP

### ISSUE THREAD

**Issue by ryanmerolle** [alsigna/netbox-software-manager#2]
I personally already run an HTTP/S container on the NetBox Host systems list all our golden firmware.  Currently, I link to said URLs for each device model.  I just prefer HTTP/HTTPS to download over FTP and SCP.  Would you be open to a toggle to allow multiple transfer protocols?

**Comment by alsigna** [comment]
done
