### ISSUE TITLE
NetBox v3.0 Support

### ISSUE THREAD

**Issue by ryanmerolle** [alsigna/netbox-software-manager#6]
As an FYI here is what changed that could impact or help the plugin:
- HTML Template updates (support change from bootstrap 3 to bootstrap 5)
- Overall UI tweaks
- Custom Queue Support for Plugins netbox-community/netbox/issues/6651

If you find any issues or have any questions feel free to hit us on the slack or add a bug /issue or add to the umbrella UI issue netbox-community/netbox/issues/6797

**Comment by edurguti** [comment]
Does this plugin work with NetBox v3.0?

**Comment by alsigna** [comment]
hi, not yet. have a plan to migrate to v3, but without any confirmed dates.
