### ISSUE TITLE
Netbox 3.2 Support

### ISSUE THREAD

**Issue by ryanmerolle** [alsigna/netbox-software-manager#7]
[NetBox 3.2.0](https://github.com/netbox-community/netbox/releases/tag/v3.2.0) was just released and has a number of [extension improvements](https://github.com/netbox-community/netbox/issues/8333).

Furthermore, a [NetBox 3.2 plugin tutorial](https://github.com/netbox-community/netbox-plugin-tutorial) was released

**Comment by danner26** [comment]
@alsigna are you still working on this? If you need assistance I would be happy to help

**Comment by alsigna** [comment]
hi @danner26, sorry for the delay on this, will try to resume work on this in a few days.
